### ISSUE TITLE
[question] Why simd Add func runs slower than go func in small size floats, such as [4]float32?

### ISSUE THREAD

**Issue by o0olele** [viterin/vek#6]
- i tried 4 different size(4,16,32,64), here is the benchmark result:
~~~shell
goos: windows
goarch: amd64
pkg: github.com/viterin/vek/internal/functions
cpu: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics     
BenchmarkADD/SIMD-4-16         	353418499	         3.427 ns/op	       0 B/op	       0 allocs/op
BenchmarkADD/NO-SIMD-4-16      	572597487	         2.174 ns/op	       0 B/op	       0 allocs/op

BenchmarkADD/SIMD-16-16        	159170994	         7.580 ns/op	       0 B/op	       0 allocs/op
BenchmarkADD/NO-SIMD-16-16     	136259923	         8.581 ns/op	       0 B/op	       0 allocs/op

BenchmarkADD/SIMD-32-16        	249333396	         4.937 ns/op	       0 B/op	       0 allocs/op
BenchmarkADD/NO-SIMD-32-16     	100000000	        15.82 ns/op	       0 B/op	       0 allocs/op

BenchmarkADD/SIMD-64-16        	133381720	         8.695 ns/op	       0 B/op	       0 allocs/op
BenchmarkADD/NO-SIMD-64-16     	39249933	        33.63 ns/op	       0 B/op	       0 allocs/op
~~~

**Comment by olivier403** [comment]
SIMD instructions process multiple numbers at once, in vek's case 256 bits or 8 float32 numbers. The SIMD add function first adds together two slices in chunks of 8 numbers using SIMD instructions, until there are fewer than 8 left, it then adds the remaining numbers one by one. In your [4]float32 example there are fewer than 8 numbers so it simply adds them one by one, exactly as the Go function.

It runs slightly slower because of the extra logic splitting the slices in multiples of 8 and a remainder, and potentially also because Go can't inline the function. So it's not really worth using SIMD functions for very small slices.
